POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "Cemre",
    "surname" : "Özören",
    "email" : "admin@admin.com",
    "phone": "5076510758",
    "password": "123456"
}